<a href="https://colab.research.google.com/github/Anitagg1/Phyton-Workshop/blob/main/wines%20prices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

red_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv', sep = ';')
red_wine['wine_type'] = 'red'
red_wine['quality_label'] = red_wine['quality'].apply(lambda value: 'low'
if value <= 5 else 'medium'
if value <= 7 else 'high')
red_wine['quality_label'] = pd.Categorical(red_wine['quality_label'],
categories=['low', 'medium', 'high'])

white_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv', sep = ';')
white_wine['wine_type'] = 'white'
white_wine['quality_label'] = white_wine['quality'].apply(lambda value: 'low'
if value <= 5 else 'medium'
if value <= 7 else 'high')
white_wine['quality_label'] = pd.Categorical(white_wine['quality_label'],
categories=['low', 'medium', 'high'])

wines = pd.concat([red_wine, white_wine])

In [3]:
wines['price'] = wines['quality_label'].apply(lambda value: '8.294, 9.816'
if value == 'low' else '9.816, 11.332'
if value == 'medium' else '11.332, 12.848')

In [4]:
wines

      fixed acidity  volatile acidity  ...  quality_label          price
0               7.4              0.70  ...            low   8.294, 9.816
1               7.8              0.88  ...            low   8.294, 9.816
2               7.8              0.76  ...            low   8.294, 9.816
3              11.2              0.28  ...         medium  9.816, 11.332
4               7.4              0.70  ...            low   8.294, 9.816
...             ...               ...  ...            ...            ...
4893            6.2              0.21  ...         medium  9.816, 11.332
4894            6.6              0.32  ...            low   8.294, 9.816
4895            6.5              0.24  ...         medium  9.816, 11.332
4896            5.5              0.29  ...         medium  9.816, 11.332
4897            6.0              0.21  ...         medium  9.816, 11.332

[6497 rows x 15 columns]